version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: testdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/var/lib/postgresql/data
  backend:
    build:
      context: backend
    ports:
      - 8080:8080
  frontend:
    image: node:10
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: yarn start
    ports:
      - 8081:8081
      - 35729:35729
